apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-k8-deployment
spec:
  selector:
    matchLabels:
      app: poc-k8
  template:
    metadata:
      labels:
        app: poc-k8
    spec:
      containers:
      - name: poc-container
        image: msalazar10/poc-webapicore:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet: 
            path: /health
            port: 80
        readinessProbe:
          httpGet:
            path: /health
            port: 80
