apiVersion: v1
kind: Service
metadata:
  name: poc-service
spec:
  selector:
    app: poc-k8
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30036
    protocol: TCP
  # - port: 80
  #   targetPort: 8080
  type: NodePort #change to LoadBalancer when set it in cloud